config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "new", to: "games#new"
  post "score", to: "games#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @letters = ('A'..'Z').to_a.sample(8)
  end

  def score
    @words = params[:word]
    @letters = params[:letters]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<ul>
  <% @letters.each do |letter| %>
    <li> <%= letter %></li>
  <% end %>
</ul>

<form action="/score" method= "post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
   <%= hidden_field_tag :letters, @letters %>
  <input type="text" name="word">
  <input type="submit" value="Submit">
</form>

app/views/games/score.html.erb
<h1>Score</h1>
<%= @words %>
<%= @letters %>


<%= link_to "Play again", score_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>